class BaseRepository:
    model = None

    def insert(self, **values): ...
    def select(self, model_id: int, **filter_by): ...
    def update(self, **values): ...
    def delete(self, model_Id: int): ...
