"""update models - attrs

Revision ID: 1347db754877
Revises: ec569752ed20
Create Date: 2026-07-05 03:47:47.519220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1347db754877'
down_revision: Union[str, Sequence[str], None] = 'ec569752ed20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluations', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('evaluations', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('meetings', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teams', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('users_team_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_team_id_fkey'), 'users', 'teams', ['team_id'], ['id'])
    op.alter_column('teams', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('meetings', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('evaluations', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('evaluations', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
