"""init db table

Revision ID: 301e6463605e
Revises: 506186dbff71
Create Date: 2026-05-31 10:13:11.440943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301e6463605e'
down_revision: Union[str, Sequence[str], None] = '506186dbff71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teams', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'created_by')
    # ### end Alembic commands ###
