"""fix TeamModel, remove unque from Model

Revision ID: 3513f6058a9c
Revises: 4963daa9a911
Create Date: 2026-07-08 01:15:31.116096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3513f6058a9c'
down_revision: Union[str, Sequence[str], None] = '4963daa9a911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('teams_created_by_key'), 'teams', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('teams_created_by_key'), 'teams', ['created_by'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
