"""update TaskModel

Revision ID: 45f05a1192aa
Revises: 3513f6058a9c
Create Date: 2026-07-08 23:46:48.442686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f05a1192aa'
down_revision: Union[str, Sequence[str], None] = '3513f6058a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
