"""update db schemas. Create schema db

Revision ID: 4963daa9a911
Revises: 1347db754877
Create Date: 2026-07-05 15:09:37.868296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4963daa9a911'
down_revision: Union[str, Sequence[str], None] = '1347db754877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tasks', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('tasks', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teams', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teams', 'invite_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'teams', ['created_by'])
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'teams', type_='unique')
    op.alter_column('teams', 'invite_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teams', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('meetings', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
