"""FIRST AFTER START

Revision ID: 592de6a9cfb8
Revises: a6e6109ad415
Create Date: 2026-07-26 22:12:18.989363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592de6a9cfb8'
down_revision: Union[str, Sequence[str], None] = 'a6e6109ad415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teams', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'created_by')
    # ### end Alembic commands ###
