"""rename password to hashed_password

Revision ID: 65bcb50dbec0
Revises: 9be4949c5d19
Create Date: 2026-07-10 22:19:19.103974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "65bcb50dbec0"
down_revision: Union[str, Sequence[str], None] = "9be4949c5d19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password", new_column_name="hashed_password")
    op.add_column(
        "users",
        sa.Column(
            "is_verified",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified")
    op.alter_column("users", "hashed_password", new_column_name="password")
    # ### end Alembic commands ###
