"""update ondelet UserModels

Revision ID: 9df58c8903a2
Revises: a706f8f81c51
Create Date: 2026-07-26 20:56:35.610377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df58c8903a2'
down_revision: Union[str, Sequence[str], None] = 'a706f8f81c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('teams_created_by_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_created_by_fkey'), 'teams', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
