"""remove ondelete task_id TaskComment

Revision ID: a31a1dfc0c84
Revises: 821f00f95da6
Create Date: 2026-07-11 21:55:30.731259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31a1dfc0c84'
down_revision: Union[str, Sequence[str], None] = '821f00f95da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('task_comments_task_id_fkey'), 'task_comments', type_='foreignkey')
    op.create_foreign_key(None, 'task_comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_comments', type_='foreignkey')
    op.create_foreign_key(op.f('task_comments_task_id_fkey'), 'task_comments', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
