"""update ondelet UserModels

Revision ID: bf426b5c8899
Revises: 9df58c8903a2
Create Date: 2026-07-26 20:57:44.775161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf426b5c8899'
down_revision: Union[str, Sequence[str], None] = '9df58c8903a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('meetings_created_by_fkey'), 'meetings', type_='foreignkey')
    op.create_foreign_key(None, 'meetings', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.create_foreign_key(op.f('meetings_created_by_fkey'), 'meetings', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
