"""update ondelet UserModels

Revision ID: de7be165377c
Revises: e1076248c43b
Create Date: 2026-07-26 20:53:07.577840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7be165377c'
down_revision: Union[str, Sequence[str], None] = 'e1076248c43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('evaluations_employee_id_fkey'), 'evaluations', type_='foreignkey')
    op.drop_constraint(op.f('evaluations_task_id_fkey'), 'evaluations', type_='foreignkey')
    op.drop_constraint(op.f('evaluations_reviewer_id_fkey'), 'evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'evaluations', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluations', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluations', 'users', ['reviewer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('teams_created_by_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_created_by_fkey'), 'teams', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('evaluations_reviewer_id_fkey'), 'evaluations', 'users', ['reviewer_id'], ['id'])
    op.create_foreign_key(op.f('evaluations_task_id_fkey'), 'evaluations', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('evaluations_employee_id_fkey'), 'evaluations', 'users', ['employee_id'], ['id'])
    # ### end Alembic commands ###
