"""update ondelet TaskModel

Revision ID: e1076248c43b
Revises: 7ab00dbc6f6c
Create Date: 2026-07-26 19:19:01.838566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1076248c43b'
down_revision: Union[str, Sequence[str], None] = '7ab00dbc6f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_created_by_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_team_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_assignee_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assignee_id_fkey'), 'tasks', 'users', ['assignee_id'], ['id'])
    op.create_foreign_key(op.f('tasks_team_id_fkey'), 'tasks', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('tasks_created_by_fkey'), 'tasks', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
