"""update datetime field timezone at TaskComments

Revision ID: e6e9073d0dce
Revises: 6e595735ab89
Create Date: 2026-07-04 23:53:06.964159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6e9073d0dce'
down_revision: Union[str, Sequence[str], None] = '6e595735ab89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_comments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('task_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_comments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('task_comments', 'updated_at')
    # ### end Alembic commands ###
