"""update meeting_participants add CASCADE

Revision ID: ec569752ed20
Revises: 932c40c97f51
Create Date: 2026-07-05 02:40:05.153238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec569752ed20'
down_revision: Union[str, Sequence[str], None] = '932c40c97f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('meeting_participants_user_id_fkey'), 'meeting_participants', type_='foreignkey')
    op.drop_constraint(op.f('meeting_participants_meeting_id_fkey'), 'meeting_participants', type_='foreignkey')
    op.create_foreign_key(None, 'meeting_participants', 'meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'meeting_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting_participants', type_='foreignkey')
    op.drop_constraint(None, 'meeting_participants', type_='foreignkey')
    op.create_foreign_key(op.f('meeting_participants_meeting_id_fkey'), 'meeting_participants', 'meetings', ['meeting_id'], ['id'])
    op.create_foreign_key(op.f('meeting_participants_user_id_fkey'), 'meeting_participants', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
